// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMpYbB_W3CRIkeCwzc4V28K3vrjSbbCX4',
    appId: '1:875258730243:web:62c1176ef6f666cb977b36',
    messagingSenderId: '875258730243',
    projectId: 'dapp-5ae3c',
    authDomain: 'dapp-5ae3c.firebaseapp.com',
    storageBucket: 'dapp-5ae3c.firebasestorage.app',
    measurementId: 'G-67JZH7EJP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXWQBR80FFPjby4mBd4SKMCjh8uGwTX5w',
    appId: '1:875258730243:android:0dc707e26e23b11e977b36',
    messagingSenderId: '875258730243',
    projectId: 'dapp-5ae3c',
    storageBucket: 'dapp-5ae3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoy5lOjYZeJN5WyJADjQoqAo3mhFz58wQ',
    appId: '1:875258730243:ios:5fd60f080d96bcda977b36',
    messagingSenderId: '875258730243',
    projectId: 'dapp-5ae3c',
    storageBucket: 'dapp-5ae3c.firebasestorage.app',
    iosBundleId: 'com.example.votingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoy5lOjYZeJN5WyJADjQoqAo3mhFz58wQ',
    appId: '1:875258730243:ios:5fd60f080d96bcda977b36',
    messagingSenderId: '875258730243',
    projectId: 'dapp-5ae3c',
    storageBucket: 'dapp-5ae3c.firebasestorage.app',
    iosBundleId: 'com.example.votingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMpYbB_W3CRIkeCwzc4V28K3vrjSbbCX4',
    appId: '1:875258730243:web:704e5a9244c45768977b36',
    messagingSenderId: '875258730243',
    projectId: 'dapp-5ae3c',
    authDomain: 'dapp-5ae3c.firebaseapp.com',
    storageBucket: 'dapp-5ae3c.firebasestorage.app',
    measurementId: 'G-7DRR687B7L',
  );
}
